Add Fabric implementation for Android
klarna-incubator/react-native-vector-drawable pull request #5
Opened 2022-06-18 07:22 UTC by zolbooo

Hello, thank you for work on this project 👋

I have updated example app to use React Native `0.69.0-rc.6`, which is the first release to enable new architecture by default. Also I have added implementation of VectorDrawable component for Fabric. I have build application with and without new arch enabled and example app seems to work correctly.

Test plan:
- [x] Fabric example app
- [x] Paper example app (built with `newArchEnabled=false` in `gradle.properties`
- [ ] iOS app (I have not built it yet, but native component import should be replaced by `View`)
- [ ] Some props could be implemented incorrectly because `RNVectorDrawableNativeComponent` and `index.d.ts` typings differ

2022-06-18 07:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/klarna-incubator/react-native-vector-drawable?pullRequest=5) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/klarna-incubator/react-native-vector-drawable?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/klarna-incubator/react-native-vector-drawable?pullRequest=5) it.</sub>

2022-06-22 14:06 UTC, zolbooo commented
Could you review this, @oblador?

2022-06-22 14:34 UTC, oblador requested changes
Absolutely fantastic PR! Added a bunch of comments, mostly minor, but I'm missing updated README instructions and maybe a mention of Fabric support.

2022-06-22 14:34 UTC, oblador commented on android/build.gradle
> +                            "REACT_ANDROID_DIR=${appProject.rootDir}/../node_modules/react-native/ReactAndroid",
This is an unsafe assumption about where react-native package is located that works with this project, but breaks mono-repos (that we use at Klarna). See this [gradle file](https://github.com/oblador/react-native-performance/blob/master/packages/react-native-performance/android/build.gradle#L15-L28) for an example on how that can be done in a more dynamic fashion. I've discussed this with Meta but no better solution in place than this from what I know.

2022-06-22 14:34 UTC, oblador commented on android/build.gradle
> +        // See: https://github.com/software-mansion/react-native-screens/blob/main/android/build.gradle#L90
Weird, but ok

2022-06-22 14:34 UTC, oblador commented on android/build.gradle
> -    if (project == rootProject) {
Any particular reason why you changed this setup?

2022-06-22 14:34 UTC, oblador commented on android/build.gradle
> +    react {
For monorepo setups I believe you need to pass reactNativeDir/codegenDir too as in the linked example

2022-06-22 14:34 UTC, oblador commented on android/src/fabric/java/com/klarna/vectordrawable/VectorDrawableManager.java
> +		implements RNVectorDrawableManagerInterface<ImageView> {
Mixing of spaces and tab indentation in this file, please make sure all java files are using 4 spaces

2022-06-22 14:34 UTC, oblador commented on android/src/main/jni/VectorDrawableComponentsRegistry.cpp
> +      makeNativeMethod("initHybrid", VectorDrawableComponentsRegistry::initHybrid),
```suggestion
    makeNativeMethod("initHybrid", VectorDrawableComponentsRegistry::initHybrid),
```

2022-06-22 14:34 UTC, oblador commented on android/src/main/jni/VectorDrawableComponentsRegistry.h
> +} // namespace facebook
```suggestion
} // namespace facebook

```

2022-06-22 14:34 UTC, oblador commented on android/src/main/jni/VectorDrawableComponentsRegistry.cpp
> +} // namespace facebook
```suggestion
} // namespace facebook

```

2022-06-22 14:34 UTC, oblador commented on android/src/main/jni/OnInit.cpp
> +}
```suggestion
}

```

2022-06-22 14:34 UTC, oblador commented on android/src/main/jni/Android.mk
> +include $(BUILD_SHARED_LIBRARY)
```suggestion
include $(BUILD_SHARED_LIBRARY)

```

2022-06-22 14:34 UTC, oblador commented on android/src/fabric/java/com/klarna/vectordrawable/VectorDrawableComponentsRegistry.java
> +}
For the pedantic smurf inside me, please always have an empty new line at the end of the file 🙏 
```suggestion
}

```

2022-06-22 14:34 UTC, oblador commented on example/package.json
> +    "react-native-codegen": "^0.69.1",
I didn't think it was necessary to explicitly include codegen/gradle-plugin dependencies

2022-06-22 14:34 UTC, oblador commented on src/RNVectorDrawableNativeComponent.ts
> +import {WithDefault} from 'react-native/Libraries/Types/CodegenTypes';
```suggestion
import { WithDefault } from 'react-native/Libraries/Types/CodegenTypes';
```

2022-06-23 08:21 UTC, oblador commented
@zolbooo I'll be going on vacation tomorrow just as a heads up. 👍

2022-06-23 08:23 UTC, zolbooo commented
Okay, I will push my commits in a few hours.

2022-06-23 09:34 UTC, zolbooo commented
Everything seems good to me now, please check 🚀

2022-07-14 10:10 UTC, oblador commented
Back from vacation now :D I tried to run the example project with fabric turned off (hence using paper), but it failed to compile with this error:
```
node_modules/@klarna/react-native-vector-drawable/android/src/paper/java/com/klarna/vectordrawable/VectorDrawableManager.java:22: error: invalid method declaration; return type required
    public ColoredViewManager(ReactApplicationContext reactContext) {
           ^
1 error
```

I didn't look much further into this error, but I'm guessing it's because codegen not being run in old architecture.

2022-07-14 11:23 UTC, zolbooo commented
> Back from vacation now :D I tried to run the example project with fabric turned off (hence using paper), but it failed to compile with this error:
> 
> ```
> 
> node_modules/@klarna/react-native-vector-drawable/android/src/paper/java/com/klarna/vectordrawable/VectorDrawableManager.java:22: error: invalid method declaration; return type required
> 
>     public ColoredViewManager(ReactApplicationContext reactContext) {
> 
>            ^
> 
> 1 error
> 
> ```
> 
> 
> 
> I didn't look much further into this error, but I'm guessing it's because codegen not being run in old architecture. 

Oops, I forgot to rename constructor in Paper implementation. Please check the latest commit.

2022-07-14 12:02 UTC, oblador commented
Still same error for me 🤔 Did you manage to run this locally?

2022-07-14 23:53 UTC, zolbooo commented
My bad, I was editing `node_modules` in example instead of editing library files directly. Now it compiles on both archtitectures. Also added support for M1 devices in [4b47a91](https://github.com/klarna-incubator/react-native-vector-drawable/pull/5/commits/4b47a91d9df47057fb36c954323f60a7bb1c6e64).

2022-07-15 08:21 UTC, oblador approved these changes

2022-07-15 08:22 UTC, merged